spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_db
    username: root
    password: '0000'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  logging:
    level:
      org.hibernate.SQL: DEBUG

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
  undertow:
    io-threads: 4
    worker-threads: 20
    buffer-size: 1024
    direct-buffers: true

springdoc:
  swagger-ui:
    enabled: true